                       <fieldset>
                        <input type="checkbox" name="frameworks[]" id="sass" value="Sass"/>
                        <label for="sass">Sass</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="frameworks[]" id="bootstrap" value="Bootstrap"/>
                        <label for="bootstrap">Bootstrap</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="frameworks[]" id="symfony" value="Symfony"/>
                        <label for="symfony">Symfony</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="frameworks[]" id="laravel" value="Laravel"/>
                        <label for="laravel">Laravel</label>
                    </fieldset>