                        <fieldset>
                            <label for="nom">Nom</label>
                            <input type="text" name="nom" id="nom" />
                        </fieldset>
                        <fieldset>
                            <label for="prenom">Prénom</label>
                            <input type="text" name="prenom" id="prenom" />
                        </fieldset>
                        <fieldset>
                            <label for="email">Email</label>
                            <input type="email" name="email" id="email" />
                        </fieldset>
                        <fieldset>
                            <label for="telephone">Téléphone</label>
                            <input type="text" name="telephone" id="telephone" />
                        </fieldset>
                        <fieldset>
                            <label for="linkedin">LinkedIn</label>
                            <input type="text" name="linkedin" id="linkedin" />
                        </fieldset>
                        <fieldset>
                            <label for="github">GitHub</label>
                            <input type="text" name="github" id="github" />
                        </fieldset>
                        <fieldset id="textarea">
                            <label for="biographie">Biographie</label>
                            <textarea name="biographie" id="biographie">
                            </textarea>
                        </fieldset>
                        <fieldset>
                            <label for="loisir-1">Loisir 1</label>
                            <input type="text" name="loisir-1" id="loisir-1" />
                        </fieldset>
                        <fieldset>
                            <label for="loisir-2">Loisir 2</label>
                            <input type="text" name="loisir-2" id="loisir-2" />
                        </fieldset>
                        <fieldset>
                            <label for="loisir-3">Loisir 3</label>
                            <input type="text" name="loisir-3" id="loisir-3" />
                        </fieldset>
                        <fieldset>
                            <label for="loisir-4">Loisir 4</label>
                            <input type="text" name="loisir-4" id="loisir-4" />
                        </fieldset>