                    <fieldset>
                        <input type="checkbox" name="language[]" id="fr" value="Français"/>
                        <label for="fr">Français</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="language[]" id="en" value="Anglais"/>
                        <label for="en">Anglais</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="language[]" id="arabe" value="Arabe"/>
                        <label for="arabe">Arabe</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="language[]" id="breton" value="Breton"/>
                        <label for="breton">Breton</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="language[]" id="espagnol" value="Espagnol"/>
                        <label for="espagnol">Espagnol</label>
                    </fieldset>