                    <fieldset>
                        <input type="checkbox" name="software[]" id="ps" value="Photoshop"/>
                        <label for="ps">Photoshop</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="software[]" id="il" value="Illustrator"/>
                        <label for="il">Illustrator</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="software[]" id="xd" value="XD"/>
                        <label for="xd">XD</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="software[]" id="figma" value="Figma"/>
                        <label for="figma">Figma</label>
                    </fieldset>