
                    <fieldset>
                        <input type="checkbox" name="lang[]" id="html" value="HTML"/>
                        <label for="html">HTML</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="lang[]" id="css" value="CSS"/>
                        <label for="css">CSS</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="lang[]" id="js" value="JavaScript"/>
                        <label for="js">JavaScript</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="lang[]" id="php" value="PHP"/>
                        <label for="php">PHP</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="lang[]" id="sql" value="SQL"/>
                        <label for="sql">SQL</label>
                    </fieldset>